[package]
name = "test_support"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"
publish = false

[features]
default = ["anyrender_vello"]
anyrender_vello = []
anyrender_vello_cpu = []
anyrender_skia = []

[dependencies]
testdir = "0.10.0"
cfg-if = { workspace = true }
image = { version = "0.25", default-features = false, features = ["png"] }  # Version required by blitz-dom
image-compare = "0.5.0"
webvfx = { path = "../webvfx" }

[lints]
workspace = true
