[package]
name = "webvfx"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
default-run = "webvfx_viewer"

[[bin]]
name = "webvfx_viewer"
path = "src/main.rs"

[dependencies]
frei0r-rs2 = { git = "https://github.com/rectalogic/frei0r-rs.git", tag = "2.3.0" }
anyhow = { workspace = true }
cfg-if = { workspace = true }
data-url = "0.3.2"
anyrender = "0.13.0"
anyrender_vello = { version = "0.14.0", default-features = false }
peniko = "0.6"
style = { version = "0.21.0", package = "stylo" }
wgpu = "29"
wgpu_context = "0.9"
winit = { version = "=0.31.0-beta.3" } # match blitz requirement
argh = "0.1"
serde_json = "1.0.145"
tera = "1.20.1"
tracing-subscriber = { version = "0.3.22", optional = true }

# Don't depend on blitz meta-crate
# https://github.com/DioxusLabs/blitz/issues/301
blitz-dom = { git = "https://github.com/DioxusLabs/blitz.git", rev = "c20690f", default-features = false, features = ["svg", "system-fonts", "woff", "custom-widget"] }
blitz-paint = { git = "https://github.com/DioxusLabs/blitz.git", rev = "c20690f", default-features = false, features = ["svg", "custom-widget"] }
blitz-traits = { git = "https://github.com/DioxusLabs/blitz.git", rev = "c20690f", default-features = false }
blitz-html = { git = "https://github.com/DioxusLabs/blitz.git", rev = "c20690f", default-features = false }
blitz-net = { git = "https://github.com/DioxusLabs/blitz.git", rev = "c20690f", default-features = false }
blitz-shell = { git = "https://github.com/DioxusLabs/blitz.git", rev = "c20690f", default-features = false, features = ["custom-widget"] }
reqwest = { version = "0.13", features = ["blocking"] }

[dev-dependencies]
test_support = { path = "../test_support" }

[features]
tracing = ["blitz-dom/tracing", "blitz-paint/tracing", "blitz-shell/tracing", "dep:tracing-subscriber"]

[lints]
workspace = true
