name: Build and test

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libfontconfig1-dev

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v2

      - name: Cache dependencies
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check
        run: cargo check --locked --workspace --no-default-features

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v2
        with:
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --check

  clippy:
    name: Clippy
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libfontconfig1-dev

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v2
        with:
          components: clippy

      - name: Cache dependencies
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run clippy
        run: cargo clippy --locked --workspace --all-targets -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install \
            libfontconfig1-dev \
            fonts-liberation \
            libavcodec-dev \
            libavfilter-dev \
            libavformat-dev \
            libavutil-dev \
            libglvnd-dev \
            libglx-mesa0 \
            libnss3 \
            libpulse0 \
            libvulkan-dev \
            libxcomposite1 \
            libxdamage1 \
            libxkbcommon-dev \
            libxi6 \
            libxrandr2 \
            libxrender1 \
            libxtst6 \
            mesa-vulkan-drivers \
            xvfb

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v2

      - name: Cache dependencies
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: |
            exec /usr/bin/xvfb-run --server-args="-screen 0 640x480x24 -nolisten unix" cargo test --locked --workspace --no-default-features

      - name: Upload Failed Artifacts
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: failed-output
          path: target/testdir-current
